'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace GridWebBasics

    Partial Public Class ApplyEditModes

        '''<summary>
        '''CheckBox1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CheckBox1 As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''Panel2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Panel2 As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''CheckBox2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CheckBox2 As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''Label1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBox1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBox1 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''Panel3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Panel3 As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''CheckBox3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CheckBox3 As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''Label2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label2 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TextBox2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TextBox2 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''GridWeb1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents GridWeb1 As Global.Aspose.Cells.GridWeb.GridWeb
    End Class
End Namespace
