'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Worksheets

    Partial Public Class ExportDataTable

        '''<summary>
        '''btnExportDataTable control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnExportDataTable As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''trResult control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trResult As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''GridView1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents GridView1 As Global.System.Web.UI.WebControls.GridView

        '''<summary>
        '''GridView2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents GridView2 As Global.System.Web.UI.WebControls.GridView

        '''<summary>
        '''GridWeb1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents GridWeb1 As Global.Aspose.Cells.GridWeb.GridWeb
    End Class
End Namespace
