'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Worksheets

    Partial Public Class ManageComments

        '''<summary>
        '''btnAddComments control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnAddComments As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnUpdateComments control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnUpdateComments As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnRemoveComments control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnRemoveComments As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''GridWeb1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents GridWeb1 As Global.Aspose.Cells.GridWeb.GridWeb
    End Class
End Namespace
